<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719153906 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE requirement_mappings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, coverage_percent INT NOT NULL, inherit_evidence BOOLEAN NOT NULL, rationale TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, source_requirement_id INT NOT NULL, target_requirement_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71AC83FA32C8A3DE ON requirement_mappings (organization_id)');
        $this->addSql('CREATE INDEX IDX_71AC83FAD82E03D2 ON requirement_mappings (source_requirement_id)');
        $this->addSql('CREATE INDEX IDX_71AC83FAC72D605E ON requirement_mappings (target_requirement_id)');
        $this->addSql('CREATE INDEX IDX_71AC83FAB03A8386 ON requirement_mappings (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_requirement_mapping_org_pair ON requirement_mappings (organization_id, source_requirement_id, target_requirement_id)');
        $this->addSql('CREATE TABLE security_control_tests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, frequency VARCHAR(30) NOT NULL, result VARCHAR(30) NOT NULL, procedure TEXT NOT NULL, sample_description TEXT DEFAULT NULL, sample_size INT DEFAULT NULL, conclusion TEXT DEFAULT NULL, evidence JSON NOT NULL, performed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, next_review_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, control_id INT NOT NULL, tester_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2070EB1D32C8A3DE ON security_control_tests (organization_id)');
        $this->addSql('CREATE INDEX IDX_2070EB1D32BEC70E ON security_control_tests (control_id)');
        $this->addSql('CREATE INDEX IDX_2070EB1D979A21C1 ON security_control_tests (tester_id)');
        $this->addSql('CREATE TABLE statement_of_applicability_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, applicable BOOLEAN NOT NULL, justification TEXT DEFAULT NULL, implementation_status VARCHAR(30) NOT NULL, next_review_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, evidence JSON NOT NULL, statement_id INT NOT NULL, requirement_id INT NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_771258BE849CB65B ON statement_of_applicability_items (statement_id)');
        $this->addSql('CREATE INDEX IDX_771258BE7B576F77 ON statement_of_applicability_items (requirement_id)');
        $this->addSql('CREATE INDEX IDX_771258BE7E3C61F9 ON statement_of_applicability_items (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_soa_requirement ON statement_of_applicability_items (statement_id, requirement_id)');
        $this->addSql('CREATE TABLE soa_item_controls (statement_of_applicability_item_id INT NOT NULL, security_control_id INT NOT NULL, PRIMARY KEY (statement_of_applicability_item_id, security_control_id))');
        $this->addSql('CREATE INDEX IDX_5AA46DE19198F536 ON soa_item_controls (statement_of_applicability_item_id)');
        $this->addSql('CREATE INDEX IDX_5AA46DE1F26C157B ON soa_item_controls (security_control_id)');
        $this->addSql('CREATE TABLE soa_item_risks (statement_of_applicability_item_id INT NOT NULL, risk_scenario_id INT NOT NULL, PRIMARY KEY (statement_of_applicability_item_id, risk_scenario_id))');
        $this->addSql('CREATE INDEX IDX_E50622C99198F536 ON soa_item_risks (statement_of_applicability_item_id)');
        $this->addSql('CREATE INDEX IDX_E50622C93A23418E ON soa_item_risks (risk_scenario_id)');
        $this->addSql('CREATE TABLE soa_item_actions (statement_of_applicability_item_id INT NOT NULL, action_plan_id INT NOT NULL, PRIMARY KEY (statement_of_applicability_item_id, action_plan_id))');
        $this->addSql('CREATE INDEX IDX_464B570F9198F536 ON soa_item_actions (statement_of_applicability_item_id)');
        $this->addSql('CREATE INDEX IDX_464B570F323B8A7A ON soa_item_actions (action_plan_id)');
        $this->addSql('CREATE TABLE statements_of_applicability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, version_number INT NOT NULL, status VARCHAR(20) NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, framework_id INT NOT NULL, scope_id INT NOT NULL, owner_id INT NOT NULL, previous_version_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAE742D732C8A3DE ON statements_of_applicability (organization_id)');
        $this->addSql('CREATE INDEX IDX_EAE742D737AECF72 ON statements_of_applicability (framework_id)');
        $this->addSql('CREATE INDEX IDX_EAE742D7682B5931 ON statements_of_applicability (scope_id)');
        $this->addSql('CREATE INDEX IDX_EAE742D77E3C61F9 ON statements_of_applicability (owner_id)');
        $this->addSql('CREATE INDEX IDX_EAE742D73CBC65BC ON statements_of_applicability (previous_version_id)');
        $this->addSql('CREATE INDEX IDX_EAE742D72D234F6A ON statements_of_applicability (approved_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_soa_org_framework_scope_version ON statements_of_applicability (organization_id, framework_id, scope_id, version_number)');
        $this->addSql('ALTER TABLE requirement_mappings ADD CONSTRAINT FK_71AC83FA32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE requirement_mappings ADD CONSTRAINT FK_71AC83FAD82E03D2 FOREIGN KEY (source_requirement_id) REFERENCES requirements (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE requirement_mappings ADD CONSTRAINT FK_71AC83FAC72D605E FOREIGN KEY (target_requirement_id) REFERENCES requirements (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE requirement_mappings ADD CONSTRAINT FK_71AC83FAB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_control_tests ADD CONSTRAINT FK_2070EB1D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_control_tests ADD CONSTRAINT FK_2070EB1D32BEC70E FOREIGN KEY (control_id) REFERENCES security_controls (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_control_tests ADD CONSTRAINT FK_2070EB1D979A21C1 FOREIGN KEY (tester_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statement_of_applicability_items ADD CONSTRAINT FK_771258BE849CB65B FOREIGN KEY (statement_id) REFERENCES statements_of_applicability (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statement_of_applicability_items ADD CONSTRAINT FK_771258BE7B576F77 FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statement_of_applicability_items ADD CONSTRAINT FK_771258BE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE soa_item_controls ADD CONSTRAINT FK_5AA46DE19198F536 FOREIGN KEY (statement_of_applicability_item_id) REFERENCES statement_of_applicability_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soa_item_controls ADD CONSTRAINT FK_5AA46DE1F26C157B FOREIGN KEY (security_control_id) REFERENCES security_controls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soa_item_risks ADD CONSTRAINT FK_E50622C99198F536 FOREIGN KEY (statement_of_applicability_item_id) REFERENCES statement_of_applicability_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soa_item_risks ADD CONSTRAINT FK_E50622C93A23418E FOREIGN KEY (risk_scenario_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soa_item_actions ADD CONSTRAINT FK_464B570F9198F536 FOREIGN KEY (statement_of_applicability_item_id) REFERENCES statement_of_applicability_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE soa_item_actions ADD CONSTRAINT FK_464B570F323B8A7A FOREIGN KEY (action_plan_id) REFERENCES action_plans (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D737AECF72 FOREIGN KEY (framework_id) REFERENCES frameworks (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D7682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D77E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D73CBC65BC FOREIGN KEY (previous_version_id) REFERENCES statements_of_applicability (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE statements_of_applicability ADD CONSTRAINT FK_EAE742D72D234F6A FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE requirement_mappings DROP CONSTRAINT FK_71AC83FA32C8A3DE');
        $this->addSql('ALTER TABLE requirement_mappings DROP CONSTRAINT FK_71AC83FAD82E03D2');
        $this->addSql('ALTER TABLE requirement_mappings DROP CONSTRAINT FK_71AC83FAC72D605E');
        $this->addSql('ALTER TABLE requirement_mappings DROP CONSTRAINT FK_71AC83FAB03A8386');
        $this->addSql('ALTER TABLE security_control_tests DROP CONSTRAINT FK_2070EB1D32C8A3DE');
        $this->addSql('ALTER TABLE security_control_tests DROP CONSTRAINT FK_2070EB1D32BEC70E');
        $this->addSql('ALTER TABLE security_control_tests DROP CONSTRAINT FK_2070EB1D979A21C1');
        $this->addSql('ALTER TABLE statement_of_applicability_items DROP CONSTRAINT FK_771258BE849CB65B');
        $this->addSql('ALTER TABLE statement_of_applicability_items DROP CONSTRAINT FK_771258BE7B576F77');
        $this->addSql('ALTER TABLE statement_of_applicability_items DROP CONSTRAINT FK_771258BE7E3C61F9');
        $this->addSql('ALTER TABLE soa_item_controls DROP CONSTRAINT FK_5AA46DE19198F536');
        $this->addSql('ALTER TABLE soa_item_controls DROP CONSTRAINT FK_5AA46DE1F26C157B');
        $this->addSql('ALTER TABLE soa_item_risks DROP CONSTRAINT FK_E50622C99198F536');
        $this->addSql('ALTER TABLE soa_item_risks DROP CONSTRAINT FK_E50622C93A23418E');
        $this->addSql('ALTER TABLE soa_item_actions DROP CONSTRAINT FK_464B570F9198F536');
        $this->addSql('ALTER TABLE soa_item_actions DROP CONSTRAINT FK_464B570F323B8A7A');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D732C8A3DE');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D737AECF72');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D7682B5931');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D77E3C61F9');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D73CBC65BC');
        $this->addSql('ALTER TABLE statements_of_applicability DROP CONSTRAINT FK_EAE742D72D234F6A');
        $this->addSql('DROP TABLE requirement_mappings');
        $this->addSql('DROP TABLE security_control_tests');
        $this->addSql('DROP TABLE statement_of_applicability_items');
        $this->addSql('DROP TABLE soa_item_controls');
        $this->addSql('DROP TABLE soa_item_risks');
        $this->addSql('DROP TABLE soa_item_actions');
        $this->addSql('DROP TABLE statements_of_applicability');
    }
}
