<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute sessions révocables et jetons de récupération de compte';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD failed_login_attempts INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE users ALTER failed_login_attempts DROP DEFAULT');
        $this->addSql('ALTER TABLE users ADD locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE TABLE auth_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, public_id VARCHAR(32) NOT NULL, refresh_token_hash VARCHAR(64) NOT NULL, user_agent VARCHAR(255) NOT NULL, ip_address VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BE9A1A95A76ED395 ON auth_sessions (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_session_public_id ON auth_sessions (public_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_session_token ON auth_sessions (refresh_token_hash)');
        $this->addSql('ALTER TABLE auth_sessions ADD CONSTRAINT FK_AUTH_SESSION_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE password_reset_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3967A216A76ED395 ON password_reset_tokens (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_password_reset_token ON password_reset_tokens (token_hash)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT FK_PASSWORD_RESET_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE auth_sessions');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('ALTER TABLE users DROP failed_login_attempts');
        $this->addSql('ALTER TABLE users DROP locked_until');
    }
}
