<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719162556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tenant-scoped identity providers, service credentials and webhook integrations.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE platform_integrations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, provider VARCHAR(30) NOT NULL, name VARCHAR(120) NOT NULL, configuration JSON NOT NULL, credential_prefix VARCHAR(16) DEFAULT NULL, secret_hash VARCHAR(64) DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34D3FDE732C8A3DE ON platform_integrations (organization_id)');
        $this->addSql('CREATE INDEX idx_integration_tenant_type ON platform_integrations (organization_id, type, enabled)');
        $this->addSql('ALTER TABLE platform_integrations ADD CONSTRAINT FK_34D3FDE732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE platform_integrations DROP CONSTRAINT FK_34D3FDE732C8A3DE');
        $this->addSql('DROP TABLE platform_integrations');
    }
}
