<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719120758 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la gestion documentaire ISMS, les versions, ACL et partages externes.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE isms_document_acl (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permission VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F293F29C33F7837 ON isms_document_acl (document_id)');
        $this->addSql('CREATE INDEX IDX_3F293F29A76ED395 ON isms_document_acl (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_isms_document_acl_user ON isms_document_acl (document_id, user_id)');
        $this->addSql('CREATE TABLE isms_document_shares (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, password_hash VARCHAR(255) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN NOT NULL, last_accessed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, access_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FE65F14C33F7837 ON isms_document_shares (document_id)');
        $this->addSql('CREATE INDEX IDX_9FE65F14B03A8386 ON isms_document_shares (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_isms_share_token ON isms_document_shares (token_hash)');
        $this->addSql('CREATE TABLE isms_document_versions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number INT NOT NULL, content TEXT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_682EA30BC33F7837 ON isms_document_versions (document_id)');
        $this->addSql('CREATE INDEX IDX_682EA30BF675F31B ON isms_document_versions (author_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_isms_document_version ON isms_document_versions (document_id, version_number)');
        $this->addSql('CREATE TABLE isms_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, category VARCHAR(80) NOT NULL, status VARCHAR(20) NOT NULL, classification VARCHAR(20) NOT NULL, visibility VARCHAR(20) NOT NULL, content TEXT NOT NULL, current_version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2995FB1332C8A3DE ON isms_documents (organization_id)');
        $this->addSql('CREATE INDEX IDX_2995FB137E3C61F9 ON isms_documents (owner_id)');
        $this->addSql('CREATE INDEX idx_isms_document_org_status ON isms_documents (organization_id, status)');
        $this->addSql('ALTER TABLE isms_document_acl ADD CONSTRAINT FK_3F293F29C33F7837 FOREIGN KEY (document_id) REFERENCES isms_documents (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_document_acl ADD CONSTRAINT FK_3F293F29A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_document_shares ADD CONSTRAINT FK_9FE65F14C33F7837 FOREIGN KEY (document_id) REFERENCES isms_documents (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_document_shares ADD CONSTRAINT FK_9FE65F14B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_document_versions ADD CONSTRAINT FK_682EA30BC33F7837 FOREIGN KEY (document_id) REFERENCES isms_documents (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_document_versions ADD CONSTRAINT FK_682EA30BF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_documents ADD CONSTRAINT FK_2995FB1332C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE isms_documents ADD CONSTRAINT FK_2995FB137E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE isms_document_acl DROP CONSTRAINT FK_3F293F29C33F7837');
        $this->addSql('ALTER TABLE isms_document_acl DROP CONSTRAINT FK_3F293F29A76ED395');
        $this->addSql('ALTER TABLE isms_document_shares DROP CONSTRAINT FK_9FE65F14C33F7837');
        $this->addSql('ALTER TABLE isms_document_shares DROP CONSTRAINT FK_9FE65F14B03A8386');
        $this->addSql('ALTER TABLE isms_document_versions DROP CONSTRAINT FK_682EA30BC33F7837');
        $this->addSql('ALTER TABLE isms_document_versions DROP CONSTRAINT FK_682EA30BF675F31B');
        $this->addSql('ALTER TABLE isms_documents DROP CONSTRAINT FK_2995FB1332C8A3DE');
        $this->addSql('ALTER TABLE isms_documents DROP CONSTRAINT FK_2995FB137E3C61F9');
        $this->addSql('DROP TABLE isms_document_acl');
        $this->addSql('DROP TABLE isms_document_shares');
        $this->addSql('DROP TABLE isms_document_versions');
        $this->addSql('DROP TABLE isms_documents');
    }
}
