<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719161427 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE regulatory_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(220) NOT NULL, status VARCHAR(20) NOT NULL, details JSON NOT NULL, evidence JSON NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FE9190232C8A3DE ON regulatory_records (organization_id)');
        $this->addSql('CREATE INDEX IDX_6FE919027E3C61F9 ON regulatory_records (owner_id)');
        $this->addSql('CREATE INDEX IDX_6FE919022D234F6A ON regulatory_records (approved_by_id)');
        $this->addSql('ALTER TABLE regulatory_records ADD CONSTRAINT FK_6FE9190232C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE regulatory_records ADD CONSTRAINT FK_6FE919027E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE regulatory_records ADD CONSTRAINT FK_6FE919022D234F6A FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE regulatory_records DROP CONSTRAINT FK_6FE9190232C8A3DE');
        $this->addSql('ALTER TABLE regulatory_records DROP CONSTRAINT FK_6FE919027E3C61F9');
        $this->addSql('ALTER TABLE regulatory_records DROP CONSTRAINT FK_6FE919022D234F6A');
        $this->addSql('DROP TABLE regulatory_records');
    }
}
