<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719092527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les plans d’action, commentaires et notifications.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE action_comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, action_plan_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8849E64C323B8A7A ON action_comments (action_plan_id)');
        $this->addSql('CREATE INDEX IDX_8849E64CF675F31B ON action_comments (author_id)');
        $this->addSql('CREATE TABLE action_plans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completion_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, progress INT NOT NULL, estimated_cost NUMERIC(12, 2) DEFAULT NULL, actual_cost NUMERIC(12, 2) DEFAULT NULL, expected_risk_reduction INT DEFAULT NULL, evidence JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, related_risk_id INT NOT NULL, related_control_id INT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2A9546D32C8A3DE ON action_plans (organization_id)');
        $this->addSql('CREATE INDEX IDX_D2A9546D3D2C7C74 ON action_plans (related_risk_id)');
        $this->addSql('CREATE INDEX IDX_D2A9546DB873CFBE ON action_plans (related_control_id)');
        $this->addSql('CREATE INDEX IDX_D2A9546D7E3C61F9 ON action_plans (owner_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, link VARCHAR(255) DEFAULT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D332C8A3DE ON notifications (organization_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D3E92F8F78 ON notifications (recipient_id)');
        $this->addSql('ALTER TABLE action_comments ADD CONSTRAINT FK_8849E64C323B8A7A FOREIGN KEY (action_plan_id) REFERENCES action_plans (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action_comments ADD CONSTRAINT FK_8849E64CF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action_plans ADD CONSTRAINT FK_D2A9546D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action_plans ADD CONSTRAINT FK_D2A9546D3D2C7C74 FOREIGN KEY (related_risk_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action_plans ADD CONSTRAINT FK_D2A9546DB873CFBE FOREIGN KEY (related_control_id) REFERENCES security_controls (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE action_plans ADD CONSTRAINT FK_D2A9546D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D332C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE action_comments DROP CONSTRAINT FK_8849E64C323B8A7A');
        $this->addSql('ALTER TABLE action_comments DROP CONSTRAINT FK_8849E64CF675F31B');
        $this->addSql('ALTER TABLE action_plans DROP CONSTRAINT FK_D2A9546D32C8A3DE');
        $this->addSql('ALTER TABLE action_plans DROP CONSTRAINT FK_D2A9546D3D2C7C74');
        $this->addSql('ALTER TABLE action_plans DROP CONSTRAINT FK_D2A9546DB873CFBE');
        $this->addSql('ALTER TABLE action_plans DROP CONSTRAINT FK_D2A9546D7E3C61F9');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D332C8A3DE');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3E92F8F78');
        $this->addSql('DROP TABLE action_comments');
        $this->addSql('DROP TABLE action_plans');
        $this->addSql('DROP TABLE notifications');
    }
}
