<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719155116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_engagements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, independence_statement TEXT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, final_report_reference VARCHAR(255) DEFAULT NULL, program_id INT NOT NULL, scope_id INT NOT NULL, lead_auditor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3772E0993EB8070A ON audit_engagements (program_id)');
        $this->addSql('CREATE INDEX IDX_3772E099682B5931 ON audit_engagements (scope_id)');
        $this->addSql('CREATE INDEX IDX_3772E099D668E637 ON audit_engagements (lead_auditor_id)');
        $this->addSql('CREATE TABLE audit_engagement_team (audit_engagement_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (audit_engagement_id, user_id))');
        $this->addSql('CREATE INDEX IDX_CCFA4EF8EE73C8D ON audit_engagement_team (audit_engagement_id)');
        $this->addSql('CREATE INDEX IDX_CCFA4EFA76ED395 ON audit_engagement_team (user_id)');
        $this->addSql('CREATE TABLE audit_findings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(220) NOT NULL, description TEXT NOT NULL, evidence JSON NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(30) NOT NULL, root_cause TEXT DEFAULT NULL, correction TEXT DEFAULT NULL, corrective_action TEXT DEFAULT NULL, preventive_action TEXT DEFAULT NULL, effectiveness_conclusion TEXT DEFAULT NULL, effectiveness_validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, engagement_id INT NOT NULL, owner_id INT NOT NULL, effectiveness_validated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84071068D30F6F97 ON audit_findings (engagement_id)');
        $this->addSql('CREATE INDEX IDX_840710687E3C61F9 ON audit_findings (owner_id)');
        $this->addSql('CREATE INDEX IDX_84071068DEF3BC77 ON audit_findings (effectiveness_validated_by_id)');
        $this->addSql('CREATE TABLE audit_programs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, title VARCHAR(200) NOT NULL, objectives TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A15D36AC32C8A3DE ON audit_programs (organization_id)');
        $this->addSql('CREATE INDEX IDX_A15D36AC7E3C61F9 ON audit_programs (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_audit_program_org_year ON audit_programs (organization_id, year)');
        $this->addSql('ALTER TABLE audit_engagements ADD CONSTRAINT FK_3772E0993EB8070A FOREIGN KEY (program_id) REFERENCES audit_programs (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_engagements ADD CONSTRAINT FK_3772E099682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_engagements ADD CONSTRAINT FK_3772E099D668E637 FOREIGN KEY (lead_auditor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_engagement_team ADD CONSTRAINT FK_CCFA4EF8EE73C8D FOREIGN KEY (audit_engagement_id) REFERENCES audit_engagements (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE audit_engagement_team ADD CONSTRAINT FK_CCFA4EFA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE audit_findings ADD CONSTRAINT FK_84071068D30F6F97 FOREIGN KEY (engagement_id) REFERENCES audit_engagements (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_findings ADD CONSTRAINT FK_840710687E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_findings ADD CONSTRAINT FK_84071068DEF3BC77 FOREIGN KEY (effectiveness_validated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_programs ADD CONSTRAINT FK_A15D36AC32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_programs ADD CONSTRAINT FK_A15D36AC7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_engagements DROP CONSTRAINT FK_3772E0993EB8070A');
        $this->addSql('ALTER TABLE audit_engagements DROP CONSTRAINT FK_3772E099682B5931');
        $this->addSql('ALTER TABLE audit_engagements DROP CONSTRAINT FK_3772E099D668E637');
        $this->addSql('ALTER TABLE audit_engagement_team DROP CONSTRAINT FK_CCFA4EF8EE73C8D');
        $this->addSql('ALTER TABLE audit_engagement_team DROP CONSTRAINT FK_CCFA4EFA76ED395');
        $this->addSql('ALTER TABLE audit_findings DROP CONSTRAINT FK_84071068D30F6F97');
        $this->addSql('ALTER TABLE audit_findings DROP CONSTRAINT FK_840710687E3C61F9');
        $this->addSql('ALTER TABLE audit_findings DROP CONSTRAINT FK_84071068DEF3BC77');
        $this->addSql('ALTER TABLE audit_programs DROP CONSTRAINT FK_A15D36AC32C8A3DE');
        $this->addSql('ALTER TABLE audit_programs DROP CONSTRAINT FK_A15D36AC7E3C61F9');
        $this->addSql('DROP TABLE audit_engagements');
        $this->addSql('DROP TABLE audit_engagement_team');
        $this->addSql('DROP TABLE audit_findings');
        $this->addSql('DROP TABLE audit_programs');
    }
}
