<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le MFA utilisateur et la configuration email chiffrée par organisation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD mfa_secret TEXT DEFAULT NULL');
        $this->addSql("ALTER TABLE users ADD mfa_recovery_codes JSON NOT NULL DEFAULT '[]'");
        $this->addSql('ALTER TABLE users ADD mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE users ALTER mfa_recovery_codes DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER mfa_enabled DROP DEFAULT');
        $this->addSql('CREATE TABLE email_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, provider VARCHAR(30) NOT NULL, host VARCHAR(255) NOT NULL, port INT NOT NULL, encryption VARCHAR(20) NOT NULL, username VARCHAR(255) NOT NULL, encrypted_password TEXT DEFAULT NULL, sender_email VARCHAR(180) NOT NULL, sender_name VARCHAR(180) NOT NULL, reply_to VARCHAR(180) DEFAULT NULL, enabled BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EE23BF8C32C8A3DE ON email_settings (organization_id)');
        $this->addSql('ALTER TABLE email_settings ADD CONSTRAINT FK_EMAIL_SETTINGS_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE email_settings');
        $this->addSql('ALTER TABLE users DROP mfa_secret');
        $this->addSql('ALTER TABLE users DROP mfa_recovery_codes');
        $this->addSql('ALTER TABLE users DROP mfa_enabled');
    }
}
