<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719161944 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE executive_governance_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, title VARCHAR(220) NOT NULL, details JSON NOT NULL, status VARCHAR(20) NOT NULL, review_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_250A679632C8A3DE ON executive_governance_records (organization_id)');
        $this->addSql('CREATE INDEX IDX_250A67967E3C61F9 ON executive_governance_records (owner_id)');
        $this->addSql('ALTER TABLE executive_governance_records ADD CONSTRAINT FK_250A679632C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE executive_governance_records ADD CONSTRAINT FK_250A67967E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE executive_governance_records DROP CONSTRAINT FK_250A679632C8A3DE');
        $this->addSql('ALTER TABLE executive_governance_records DROP CONSTRAINT FK_250A67967E3C61F9');
        $this->addSql('DROP TABLE executive_governance_records');
    }
}
