<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719155907 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE supplier_assessments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, questionnaire_version INT NOT NULL, questions JSON NOT NULL, responses JSON NOT NULL, evidence JSON NOT NULL, status VARCHAR(20) NOT NULL, public_token VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, score INT NOT NULL, review_comment TEXT DEFAULT NULL, third_party_id INT NOT NULL, reviewer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_924B471BAE981E3B ON supplier_assessments (public_token)');
        $this->addSql('CREATE INDEX IDX_924B471B54C4149C ON supplier_assessments (third_party_id)');
        $this->addSql('CREATE INDEX IDX_924B471B70574616 ON supplier_assessments (reviewer_id)');
        $this->addSql('CREATE TABLE third_parties (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, contact_email VARCHAR(180) DEFAULT NULL, services TEXT DEFAULT NULL, data_categories JSON NOT NULL, criticality VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, contract_reference VARCHAR(200) DEFAULT NULL, sla VARCHAR(200) DEFAULT NULL, dependencies TEXT DEFAULT NULL, exit_plan TEXT DEFAULT NULL, contract_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_assessment_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cyber_score INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D1C441C732C8A3DE ON third_parties (organization_id)');
        $this->addSql('CREATE INDEX IDX_D1C441C77E3C61F9 ON third_parties (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_third_party_org_name ON third_parties (organization_id, name)');
        $this->addSql('ALTER TABLE supplier_assessments ADD CONSTRAINT FK_924B471B54C4149C FOREIGN KEY (third_party_id) REFERENCES third_parties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE supplier_assessments ADD CONSTRAINT FK_924B471B70574616 FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE third_parties ADD CONSTRAINT FK_D1C441C732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE third_parties ADD CONSTRAINT FK_D1C441C77E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE supplier_assessments DROP CONSTRAINT FK_924B471B54C4149C');
        $this->addSql('ALTER TABLE supplier_assessments DROP CONSTRAINT FK_924B471B70574616');
        $this->addSql('ALTER TABLE third_parties DROP CONSTRAINT FK_D1C441C732C8A3DE');
        $this->addSql('ALTER TABLE third_parties DROP CONSTRAINT FK_D1C441C77E3C61F9');
        $this->addSql('DROP TABLE supplier_assessments');
        $this->addSql('DROP TABLE third_parties');
    }
}
