<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260809150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les ateliers EBIOS RM et la matrice de permissions RBAC';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE organizations ADD role_permissions JSON DEFAULT '{}' NOT NULL");
        $this->addSql('ALTER TABLE organizations ALTER role_permissions DROP DEFAULT');
        $this->addSql('CREATE TABLE ebios_workshops (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, analysis_id INT NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, validated_by_id INT DEFAULT NULL, workshop_number INT NOT NULL, payload JSON NOT NULL, status VARCHAR(20) NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ebios_analysis_workshop ON ebios_workshops (analysis_id, workshop_number)');
        $this->addSql('CREATE INDEX IDX_5633CBFD7941003F ON ebios_workshops (analysis_id)');
        $this->addSql('CREATE INDEX IDX_5633CBFD32C8A3DE ON ebios_workshops (organization_id)');
        $this->addSql('ALTER TABLE ebios_workshops ADD CONSTRAINT FK_EBIOS_ANALYSIS FOREIGN KEY (analysis_id) REFERENCES risk_analyses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ebios_workshops ADD CONSTRAINT FK_EBIOS_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ebios_workshops ADD CONSTRAINT FK_EBIOS_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ebios_workshops ADD CONSTRAINT FK_EBIOS_VALIDATOR FOREIGN KEY (validated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ebios_workshops');
        $this->addSql('ALTER TABLE organizations DROP role_permissions');
    }
}
