<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260726090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Asset families, GRC action fields, non-conformity links and indicator time series';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE assets ADD family VARCHAR(20) DEFAULT 'SOFTWARE' NOT NULL");
        $this->addSql("UPDATE assets SET family = CASE WHEN type IN ('SERVER','NETWORK','WORKSTATION','FACILITY') THEN 'HARDWARE' WHEN type IN ('DATA','BUSINESS_PROCESS') THEN 'INFORMATION' ELSE 'SOFTWARE' END");
        $this->addSql('ALTER TABLE assets ALTER family DROP DEFAULT');
        $this->addSql('ALTER TABLE action_plans DROP CONSTRAINT FK_D2A9546D3D2C7C74');
        $this->addSql('ALTER TABLE action_plans ALTER related_risk_id DROP NOT NULL');
        $this->addSql("ALTER TABLE action_plans ADD ticket_number VARCHAR(120) DEFAULT NULL, ADD ticket_url VARCHAR(2048) DEFAULT NULL, ADD origin VARCHAR(30) DEFAULT 'OTHER' NOT NULL, ADD action_type VARCHAR(30) DEFAULT 'OTHER' NOT NULL, ADD framework_ids JSON DEFAULT '[]' NOT NULL, ADD requirement_ids JSON DEFAULT '[]' NOT NULL, ADD custom_fields JSON DEFAULT '{}' NOT NULL");
        $this->addSql('ALTER TABLE action_plans ALTER origin DROP DEFAULT, ALTER action_type DROP DEFAULT, ALTER framework_ids DROP DEFAULT, ALTER requirement_ids DROP DEFAULT, ALTER custom_fields DROP DEFAULT');
        $this->addSql('ALTER TABLE action_plans ADD CONSTRAINT FK_D2A9546D3D2C7C74 FOREIGN KEY (related_risk_id) REFERENCES risk_scenarios (id) ON DELETE SET NULL');
        $this->addSql('CREATE TABLE indicators (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, kind VARCHAR(10) NOT NULL, unit VARCHAR(40) NOT NULL, frequency VARCHAR(20) NOT NULL, formula TEXT DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, target NUMERIC(20, 6) DEFAULT NULL, thresholds JSON NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_49B719A032C8A3DE ON indicators (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_indicator_org_code ON indicators (organization_id, code)');
        $this->addSql('ALTER TABLE indicators ADD CONSTRAINT FK_INDICATOR_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE');
        $this->addSql('CREATE TABLE indicator_values (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, indicator_id INT NOT NULL, value NUMERIC(20, 6) NOT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period VARCHAR(80) DEFAULT NULL, comment TEXT DEFAULT NULL, evidence VARCHAR(2048) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, idempotency_key VARCHAR(120) NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B9B83B7F4402854A ON indicator_values (indicator_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_indicator_idempotency ON indicator_values (indicator_id, idempotency_key)');
        $this->addSql('ALTER TABLE indicator_values ADD CONSTRAINT FK_INDICATOR_VALUE_INDICATOR FOREIGN KEY (indicator_id) REFERENCES indicators (id) ON DELETE CASCADE');
        $this->addSql('CREATE TABLE action_audit_findings (action_plan_id INT NOT NULL, audit_finding_id INT NOT NULL, PRIMARY KEY(action_plan_id, audit_finding_id))');
        $this->addSql('CREATE INDEX IDX_903DBE75323B8A7A ON action_audit_findings (action_plan_id)');
        $this->addSql('CREATE INDEX IDX_903DBE753EFDAD18 ON action_audit_findings (audit_finding_id)');
        $this->addSql('ALTER TABLE action_audit_findings ADD CONSTRAINT FK_AAF_ACTION FOREIGN KEY (action_plan_id) REFERENCES action_plans (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE action_audit_findings ADD CONSTRAINT FK_AAF_FINDING FOREIGN KEY (audit_finding_id) REFERENCES audit_findings (id) ON DELETE CASCADE');
        $this->addSql('CREATE TABLE action_compliance_results (action_plan_id INT NOT NULL, compliance_result_id INT NOT NULL, PRIMARY KEY(action_plan_id, compliance_result_id))');
        $this->addSql('CREATE INDEX IDX_9B76AC89323B8A7A ON action_compliance_results (action_plan_id)');
        $this->addSql('CREATE INDEX IDX_9B76AC894FA9ACB8 ON action_compliance_results (compliance_result_id)');
        $this->addSql('ALTER TABLE action_compliance_results ADD CONSTRAINT FK_ACR_ACTION FOREIGN KEY (action_plan_id) REFERENCES action_plans (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE action_compliance_results ADD CONSTRAINT FK_ACR_RESULT FOREIGN KEY (compliance_result_id) REFERENCES compliance_results (id) ON DELETE CASCADE');
        $this->addSql('CREATE TABLE action_custom_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, field_key VARCHAR(80) NOT NULL, label VARCHAR(160) NOT NULL, type VARCHAR(20) NOT NULL, options JSON NOT NULL, display_order INT NOT NULL, visible BOOLEAN NOT NULL, required BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_71BA659032C8A3DE ON action_custom_fields (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_action_field_org_key ON action_custom_fields (organization_id, field_key)');
        $this->addSql('ALTER TABLE action_custom_fields ADD CONSTRAINT FK_ACF_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE indicator_values');
        $this->addSql('DROP TABLE indicators');
        $this->addSql('DROP TABLE action_audit_findings');
        $this->addSql('DROP TABLE action_compliance_results');
        $this->addSql('DROP TABLE action_custom_fields');
        $this->addSql('ALTER TABLE action_plans DROP ticket_number, DROP ticket_url, DROP origin, DROP action_type, DROP framework_ids, DROP requirement_ids, DROP custom_fields');
        $this->addSql('ALTER TABLE action_plans ALTER related_risk_id SET NOT NULL');
        $this->addSql('ALTER TABLE assets DROP family');
    }
}
