<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719102500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le journal d’audit tenant-aware.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, user_id INT DEFAULT NULL, action VARCHAR(20) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id VARCHAR(100) DEFAULT NULL, new_values JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D62F285832C8A3DE ON audit_logs (organization_id)');
        $this->addSql('CREATE INDEX IDX_D62F2858A76ED395 ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_tenant_date ON audit_logs (organization_id, created_at)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_AUDIT_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_AUDIT_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_logs');
    }
}
