<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719094322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les référentiels, exigences, évaluations et résultats de conformité.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE compliance_assessments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assessment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, global_score DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, framework_id INT NOT NULL, scope_id INT NOT NULL, assessor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_41D6650832C8A3DE ON compliance_assessments (organization_id)');
        $this->addSql('CREATE INDEX IDX_41D6650837AECF72 ON compliance_assessments (framework_id)');
        $this->addSql('CREATE INDEX IDX_41D66508682B5931 ON compliance_assessments (scope_id)');
        $this->addSql('CREATE INDEX IDX_41D66508A5E4B630 ON compliance_assessments (assessor_id)');
        $this->addSql('CREATE TABLE compliance_results (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, maturity_level INT NOT NULL, compliance_status VARCHAR(30) NOT NULL, comment TEXT DEFAULT NULL, evidence JSON NOT NULL, assessment_id INT NOT NULL, requirement_id INT NOT NULL, remediation_action_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D59059A5DD3DD5F1 ON compliance_results (assessment_id)');
        $this->addSql('CREATE INDEX IDX_D59059A57B576F77 ON compliance_results (requirement_id)');
        $this->addSql('CREATE INDEX IDX_D59059A5D8E2CBE7 ON compliance_results (remediation_action_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_assessment_requirement ON compliance_results (assessment_id, requirement_id)');
        $this->addSql('CREATE TABLE frameworks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, version VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, publisher VARCHAR(180) DEFAULT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE requirements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(120) NOT NULL, status VARCHAR(20) NOT NULL, framework_id INT NOT NULL, parent_requirement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70BEA1AA37AECF72 ON requirements (framework_id)');
        $this->addSql('CREATE INDEX IDX_70BEA1AA658A1B7C ON requirements (parent_requirement_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_framework_reference ON requirements (framework_id, reference)');
        $this->addSql('ALTER TABLE compliance_assessments ADD CONSTRAINT FK_41D6650832C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_assessments ADD CONSTRAINT FK_41D6650837AECF72 FOREIGN KEY (framework_id) REFERENCES frameworks (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_assessments ADD CONSTRAINT FK_41D66508682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_assessments ADD CONSTRAINT FK_41D66508A5E4B630 FOREIGN KEY (assessor_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_results ADD CONSTRAINT FK_D59059A5DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES compliance_assessments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_results ADD CONSTRAINT FK_D59059A57B576F77 FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compliance_results ADD CONSTRAINT FK_D59059A5D8E2CBE7 FOREIGN KEY (remediation_action_id) REFERENCES action_plans (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE requirements ADD CONSTRAINT FK_70BEA1AA37AECF72 FOREIGN KEY (framework_id) REFERENCES frameworks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE requirements ADD CONSTRAINT FK_70BEA1AA658A1B7C FOREIGN KEY (parent_requirement_id) REFERENCES requirements (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE compliance_assessments DROP CONSTRAINT FK_41D6650832C8A3DE');
        $this->addSql('ALTER TABLE compliance_assessments DROP CONSTRAINT FK_41D6650837AECF72');
        $this->addSql('ALTER TABLE compliance_assessments DROP CONSTRAINT FK_41D66508682B5931');
        $this->addSql('ALTER TABLE compliance_assessments DROP CONSTRAINT FK_41D66508A5E4B630');
        $this->addSql('ALTER TABLE compliance_results DROP CONSTRAINT FK_D59059A5DD3DD5F1');
        $this->addSql('ALTER TABLE compliance_results DROP CONSTRAINT FK_D59059A57B576F77');
        $this->addSql('ALTER TABLE compliance_results DROP CONSTRAINT FK_D59059A5D8E2CBE7');
        $this->addSql('ALTER TABLE requirements DROP CONSTRAINT FK_70BEA1AA37AECF72');
        $this->addSql('ALTER TABLE requirements DROP CONSTRAINT FK_70BEA1AA658A1B7C');
        $this->addSql('DROP TABLE compliance_assessments');
        $this->addSql('DROP TABLE compliance_results');
        $this->addSql('DROP TABLE frameworks');
        $this->addSql('DROP TABLE requirements');
    }
}
