<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add the P1 operational workspace records';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE operational_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, owner_id INT DEFAULT NULL, type VARCHAR(40) NOT NULL, title VARCHAR(220) NOT NULL, status VARCHAR(30) NOT NULL, details JSON NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_reminder_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_OPERATIONAL_ORGANIZATION ON operational_records (organization_id)');
        $this->addSql('CREATE INDEX IDX_OPERATIONAL_OWNER ON operational_records (owner_id)');
        $this->addSql('CREATE INDEX idx_operational_record_lookup ON operational_records (organization_id, type, status)');
        $this->addSql('ALTER TABLE operational_records ADD CONSTRAINT FK_OPERATIONAL_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE operational_records ADD CONSTRAINT FK_OPERATIONAL_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE operational_records');
    }
}
