<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823150000 extends AbstractMigration
{
    public function getDescription(): string { return 'Ajoute le registre de preuves versionné, haché et tenant-scoped'; }
    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE platform_integrations ADD encrypted_credential TEXT DEFAULT NULL');
        $this->addSql('CREATE TABLE evidence_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, approved_by_id INT DEFAULT NULL, supersedes_id INT DEFAULT NULL, title VARCHAR(220) NOT NULL, kind VARCHAR(30) NOT NULL, classification VARCHAR(30) NOT NULL, source_reference VARCHAR(2048) NOT NULL, sha256 VARCHAR(64) NOT NULL, version INT NOT NULL, status VARCHAR(20) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_evidence_tenant_review ON evidence_records (organization_id, status, expires_at)');
        $this->addSql('CREATE INDEX IDX_74446ED77E3C61F9 ON evidence_records (owner_id)');
        $this->addSql('CREATE INDEX IDX_74446ED72D234F6A ON evidence_records (approved_by_id)');
        $this->addSql('CREATE INDEX IDX_74446ED77A7685A8 ON evidence_records (supersedes_id)');
        foreach (['requirements' => 'requirements', 'controls' => 'security_controls', 'results' => 'compliance_results', 'actions' => 'action_plans'] as $suffix => $target) {
            $column = rtrim($suffix, 's').'_id';
            if ('requirements' === $suffix) $column = 'requirement_id';
            if ('controls' === $suffix) $column = 'security_control_id';
            if ('results' === $suffix) $column = 'compliance_result_id';
            if ('actions' === $suffix) $column = 'action_plan_id';
            $this->addSql(sprintf('CREATE TABLE evidence_%s (evidence_id INT NOT NULL, %s INT NOT NULL, PRIMARY KEY(evidence_id, %s))', $suffix, $column, $column));
            $index = ['requirements' => 'IDX_5D677F2C7B576F77', 'controls' => 'IDX_7D0DF6DBF26C157B', 'results' => 'IDX_777AD2854FA9ACB8', 'actions' => 'IDX_ED91C77E323B8A7A'][$suffix];
            $this->addSql(sprintf('CREATE INDEX %s ON evidence_%s (%s)', $index, $suffix, $column));
            $this->addSql(sprintf('ALTER TABLE evidence_%s ADD CONSTRAINT FK_EVIDENCE_%s_RECORD FOREIGN KEY (evidence_id) REFERENCES evidence_records (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE', $suffix, strtoupper($suffix)));
            $this->addSql(sprintf('ALTER TABLE evidence_%s ADD CONSTRAINT FK_EVIDENCE_%s_TARGET FOREIGN KEY (%s) REFERENCES %s (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE', $suffix, strtoupper($suffix), $column, $target));
        }
        $this->addSql('ALTER TABLE evidence_records ADD CONSTRAINT FK_EVIDENCE_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evidence_records ADD CONSTRAINT FK_EVIDENCE_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evidence_records ADD CONSTRAINT FK_EVIDENCE_APPROVER FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evidence_records ADD CONSTRAINT FK_EVIDENCE_SUPERSEDES FOREIGN KEY (supersedes_id) REFERENCES evidence_records (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE notification_outbox (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, recipient_id INT NOT NULL, notification_id INT NOT NULL, idempotency_key VARCHAR(64) NOT NULL, payload JSON NOT NULL, status VARCHAR(20) NOT NULL, attempts INT NOT NULL, last_error VARCHAR(255) DEFAULT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_outbox_key ON notification_outbox (organization_id, idempotency_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AE402B2DEF1A9D84 ON notification_outbox (notification_id)');
        $this->addSql('CREATE INDEX idx_notification_outbox_dispatch ON notification_outbox (status, available_at)');
        $this->addSql('CREATE INDEX IDX_AE402B2DE92F8F78 ON notification_outbox (recipient_id)');
        $this->addSql('ALTER TABLE notification_outbox ADD CONSTRAINT FK_OUTBOX_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_outbox ADD CONSTRAINT FK_OUTBOX_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_outbox ADD CONSTRAINT FK_OUTBOX_NOTIFICATION FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE platform_integrations DROP encrypted_credential');
        $this->addSql('DROP TABLE notification_outbox');
        foreach (['requirements', 'controls', 'results', 'actions'] as $suffix) $this->addSql('DROP TABLE evidence_'.$suffix);
        $this->addSql('DROP TABLE evidence_records');
    }
}
