<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute gouvernance, acceptations formelles et campagnes de revue des risques';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE risk_scenarios ADD family VARCHAR(100) DEFAULT 'GENERAL' NOT NULL");
        $this->addSql("ALTER TABLE risk_scenarios ADD analysis_method VARCHAR(20) DEFAULT 'SIMPLIFIED' NOT NULL");
        $this->addSql('ALTER TABLE risk_scenarios ADD strategic BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('CREATE TABLE risk_governance_policies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, domain VARCHAR(100) NOT NULL, family VARCHAR(100) NOT NULL, appetite_score INT NOT NULL, tolerance_score INT NOT NULL, capacity_score INT NOT NULL, method VARCHAR(20) NOT NULL, rationale TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_risk_policy_org_domain_family ON risk_governance_policies (organization_id, domain, family)');
        $this->addSql('CREATE INDEX IDX_RISK_POLICY_ORG ON risk_governance_policies (organization_id)');
        $this->addSql('CREATE INDEX IDX_RISK_POLICY_OWNER ON risk_governance_policies (owner_id)');
        $this->addSql('ALTER TABLE risk_governance_policies ADD CONSTRAINT FK_RISK_POLICY_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_governance_policies ADD CONSTRAINT FK_RISK_POLICY_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE risk_acceptances (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, risk_id INT NOT NULL, requested_by_id INT NOT NULL, decided_by_id INT DEFAULT NULL, justification TEXT NOT NULL, authority VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decision_comment TEXT DEFAULT NULL, evidence_reference VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RISK_ACCEPTANCE_ORG ON risk_acceptances (organization_id)');
        $this->addSql('CREATE INDEX IDX_RISK_ACCEPTANCE_RISK ON risk_acceptances (risk_id)');
        $this->addSql('CREATE INDEX IDX_RISK_ACCEPTANCE_REQUESTER ON risk_acceptances (requested_by_id)');
        $this->addSql('CREATE INDEX IDX_RISK_ACCEPTANCE_DECIDER ON risk_acceptances (decided_by_id)');
        $this->addSql('ALTER TABLE risk_acceptances ADD CONSTRAINT FK_RISK_ACCEPTANCE_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_acceptances ADD CONSTRAINT FK_RISK_ACCEPTANCE_RISK FOREIGN KEY (risk_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_acceptances ADD CONSTRAINT FK_RISK_ACCEPTANCE_REQUESTER FOREIGN KEY (requested_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_acceptances ADD CONSTRAINT FK_RISK_ACCEPTANCE_DECIDER FOREIGN KEY (decided_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE risk_review_campaigns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, coordinator_id INT NOT NULL, title VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RISK_CAMPAIGN_ORG ON risk_review_campaigns (organization_id)');
        $this->addSql('CREATE INDEX IDX_RISK_CAMPAIGN_COORDINATOR ON risk_review_campaigns (coordinator_id)');
        $this->addSql('ALTER TABLE risk_review_campaigns ADD CONSTRAINT FK_RISK_CAMPAIGN_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_review_campaigns ADD CONSTRAINT FK_RISK_CAMPAIGN_COORDINATOR FOREIGN KEY (coordinator_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE risk_reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, campaign_id INT NOT NULL, risk_id INT NOT NULL, reviewer_id INT NOT NULL, status VARCHAR(20) NOT NULL, baseline_score INT NOT NULL, reviewed_score INT DEFAULT NULL, comment TEXT DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_campaign_risk ON risk_reviews (campaign_id, risk_id)');
        $this->addSql('CREATE INDEX IDX_RISK_REVIEW_RISK ON risk_reviews (risk_id)');
        $this->addSql('CREATE INDEX IDX_RISK_REVIEW_REVIEWER ON risk_reviews (reviewer_id)');
        $this->addSql('ALTER TABLE risk_reviews ADD CONSTRAINT FK_RISK_REVIEW_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES risk_review_campaigns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_reviews ADD CONSTRAINT FK_RISK_REVIEW_RISK FOREIGN KEY (risk_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE risk_reviews ADD CONSTRAINT FK_RISK_REVIEW_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE risk_reviews');
        $this->addSql('DROP TABLE risk_review_campaigns');
        $this->addSql('DROP TABLE risk_acceptances');
        $this->addSql('DROP TABLE risk_governance_policies');
        $this->addSql('ALTER TABLE risk_scenarios DROP family');
        $this->addSql('ALTER TABLE risk_scenarios DROP analysis_method');
        $this->addSql('ALTER TABLE risk_scenarios DROP strategic');
    }
}
