<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add versioned risk analyses and governed structural artifacts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE risk_analyses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, created_by_id INT NOT NULL, approved_by_id INT DEFAULT NULL, scope_id INT DEFAULT NULL, supersedes_id INT DEFAULT NULL, analysis_key VARCHAR(100) NOT NULL, version INT NOT NULL, method VARCHAR(30) NOT NULL, title VARCHAR(180) NOT NULL, objectives JSON NOT NULL, team JSON NOT NULL, milestones JSON NOT NULL, scenario_ids JSON NOT NULL, scale JSON NOT NULL, baseline JSON NOT NULL, quality_findings JSON NOT NULL, completeness INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_analysis_version ON risk_analyses (organization_id, analysis_key, version)');
        $this->addSql('CREATE INDEX idx_analysis_tenant ON risk_analyses (organization_id, status, method)');
        $this->addSql('CREATE INDEX IDX_4AAFCB53B03A8386 ON risk_analyses (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4AAFCB532D234F6A ON risk_analyses (approved_by_id)');
        $this->addSql('CREATE INDEX IDX_4AAFCB53682B5931 ON risk_analyses (scope_id)');
        $this->addSql('CREATE INDEX IDX_4AAFCB537A7685A8 ON risk_analyses (supersedes_id)');
        $this->addSql('ALTER TABLE risk_analyses ADD CONSTRAINT FK_ANALYSIS_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_analyses ADD CONSTRAINT FK_ANALYSIS_CREATED FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE risk_analyses ADD CONSTRAINT FK_ANALYSIS_APPROVED FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk_analyses ADD CONSTRAINT FK_ANALYSIS_SCOPE FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk_analyses ADD CONSTRAINT FK_ANALYSIS_PREVIOUS FOREIGN KEY (supersedes_id) REFERENCES risk_analyses (id) ON DELETE SET NULL');
        $this->addSql('CREATE TABLE analysis_artifacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, analysis_id INT DEFAULT NULL, owner_id INT NOT NULL, approved_by_id INT DEFAULT NULL, kind VARCHAR(40) NOT NULL, title VARCHAR(160) NOT NULL, payload JSON NOT NULL, status VARCHAR(20) NOT NULL, idempotency_key VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_artifact_idempotency ON analysis_artifacts (organization_id, idempotency_key)');
        $this->addSql('CREATE INDEX idx_artifact_tenant ON analysis_artifacts (organization_id, kind, status)');
        $this->addSql('CREATE INDEX IDX_DB155FB27941003F ON analysis_artifacts (analysis_id)');
        $this->addSql('CREATE INDEX IDX_DB155FB27E3C61F9 ON analysis_artifacts (owner_id)');
        $this->addSql('CREATE INDEX IDX_DB155FB22D234F6A ON analysis_artifacts (approved_by_id)');
        $this->addSql('ALTER TABLE analysis_artifacts ADD CONSTRAINT FK_ARTIFACT_ORG FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE analysis_artifacts ADD CONSTRAINT FK_ARTIFACT_ANALYSIS FOREIGN KEY (analysis_id) REFERENCES risk_analyses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE analysis_artifacts ADD CONSTRAINT FK_ARTIFACT_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE analysis_artifacts ADD CONSTRAINT FK_ARTIFACT_APPROVED FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE analysis_artifacts');
        $this->addSql('DROP TABLE risk_analyses');
    }
}
