<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801193000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add controlled assistant proposals and versioned knowledge library';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assistant_proposals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, requested_by_id INT NOT NULL, validated_by_id INT DEFAULT NULL, kind VARCHAR(40) NOT NULL, request_data JSON NOT NULL, proposal JSON NOT NULL, sources JSON NOT NULL, source_coverage DOUBLE PRECISION NOT NULL, status VARCHAR(20) NOT NULL, validation_comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_assistant_proposal_tenant ON assistant_proposals (organization_id, kind, status)');
        $this->addSql('CREATE INDEX IDX_ASSISTANT_REQUESTED_BY ON assistant_proposals (requested_by_id)');
        $this->addSql('CREATE INDEX IDX_ASSISTANT_VALIDATED_BY ON assistant_proposals (validated_by_id)');
        $this->addSql('ALTER TABLE assistant_proposals ADD CONSTRAINT FK_ASSISTANT_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assistant_proposals ADD CONSTRAINT FK_ASSISTANT_REQUESTED_BY FOREIGN KEY (requested_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assistant_proposals ADD CONSTRAINT FK_ASSISTANT_VALIDATED_BY FOREIGN KEY (validated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE knowledge_library_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, supersedes_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, item_key VARCHAR(80) NOT NULL, kind VARCHAR(40) NOT NULL, title VARCHAR(220) NOT NULL, version_number INT NOT NULL, status VARCHAR(20) NOT NULL, content JSON NOT NULL, dependencies JSON NOT NULL, source VARCHAR(250) DEFAULT NULL, license VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_library_tenant_key_version ON knowledge_library_items (organization_id, item_key, version_number)');
        $this->addSql('CREATE INDEX idx_library_tenant_kind ON knowledge_library_items (organization_id, kind, status)');
        $this->addSql('CREATE INDEX IDX_LIBRARY_OWNER ON knowledge_library_items (owner_id)');
        $this->addSql('CREATE INDEX IDX_LIBRARY_SUPERSEDES ON knowledge_library_items (supersedes_id)');
        $this->addSql('CREATE INDEX IDX_LIBRARY_APPROVED_BY ON knowledge_library_items (approved_by_id)');
        $this->addSql('ALTER TABLE knowledge_library_items ADD CONSTRAINT FK_LIBRARY_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE knowledge_library_items ADD CONSTRAINT FK_LIBRARY_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE knowledge_library_items ADD CONSTRAINT FK_LIBRARY_SUPERSEDES FOREIGN KEY (supersedes_id) REFERENCES knowledge_library_items (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE knowledge_library_items ADD CONSTRAINT FK_LIBRARY_APPROVED_BY FOREIGN KEY (approved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE assistant_proposals');
        $this->addSql('DROP TABLE knowledge_library_items');
    }
}
