<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719085606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create scopes, assets, threats, vulnerabilities and their tenant-safe relations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(30) NOT NULL, criticality INT NOT NULL, confidentiality INT NOT NULL, integrity INT NOT NULL, availability INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT DEFAULT NULL, scope_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79D17D8E7E3C61F9 ON assets (owner_id)');
        $this->addSql('CREATE INDEX IDX_79D17D8E682B5931 ON assets (scope_id)');
        $this->addSql('CREATE INDEX IDX_79D17D8E32C8A3DE ON assets (organization_id)');
        $this->addSql('CREATE TABLE scopes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, parent_scope_id INT DEFAULT NULL, organization_id INT NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D4E330F7E6F5E0 ON scopes (parent_scope_id)');
        $this->addSql('CREATE INDEX IDX_4D4E33032C8A3DE ON scopes (organization_id)');
        $this->addSql('CREATE INDEX IDX_4D4E3307E3C61F9 ON scopes (owner_id)');
        $this->addSql('CREATE TABLE threats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) NOT NULL, source VARCHAR(180) DEFAULT NULL, status VARCHAR(20) NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_254C2F8C32C8A3DE ON threats (organization_id)');
        $this->addSql('CREATE TABLE vulnerabilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) NOT NULL, severity VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_459DFAF732C8A3DE ON vulnerabilities (organization_id)');
        $this->addSql('CREATE TABLE vulnerability_assets (vulnerability_id INT NOT NULL, asset_id INT NOT NULL, PRIMARY KEY (vulnerability_id, asset_id))');
        $this->addSql('CREATE INDEX IDX_9825750572897D8B ON vulnerability_assets (vulnerability_id)');
        $this->addSql('CREATE INDEX IDX_982575055DA1941 ON vulnerability_assets (asset_id)');
        $this->addSql('ALTER TABLE assets ADD CONSTRAINT FK_79D17D8E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assets ADD CONSTRAINT FK_79D17D8E682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assets ADD CONSTRAINT FK_79D17D8E32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scopes ADD CONSTRAINT FK_4D4E330F7E6F5E0 FOREIGN KEY (parent_scope_id) REFERENCES scopes (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scopes ADD CONSTRAINT FK_4D4E33032C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scopes ADD CONSTRAINT FK_4D4E3307E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE threats ADD CONSTRAINT FK_254C2F8C32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vulnerabilities ADD CONSTRAINT FK_459DFAF732C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vulnerability_assets ADD CONSTRAINT FK_9825750572897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vulnerability_assets ADD CONSTRAINT FK_982575055DA1941 FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE assets DROP CONSTRAINT FK_79D17D8E7E3C61F9');
        $this->addSql('ALTER TABLE assets DROP CONSTRAINT FK_79D17D8E682B5931');
        $this->addSql('ALTER TABLE assets DROP CONSTRAINT FK_79D17D8E32C8A3DE');
        $this->addSql('ALTER TABLE scopes DROP CONSTRAINT FK_4D4E330F7E6F5E0');
        $this->addSql('ALTER TABLE scopes DROP CONSTRAINT FK_4D4E33032C8A3DE');
        $this->addSql('ALTER TABLE scopes DROP CONSTRAINT FK_4D4E3307E3C61F9');
        $this->addSql('ALTER TABLE threats DROP CONSTRAINT FK_254C2F8C32C8A3DE');
        $this->addSql('ALTER TABLE vulnerabilities DROP CONSTRAINT FK_459DFAF732C8A3DE');
        $this->addSql('ALTER TABLE vulnerability_assets DROP CONSTRAINT FK_9825750572897D8B');
        $this->addSql('ALTER TABLE vulnerability_assets DROP CONSTRAINT FK_982575055DA1941');
        $this->addSql('DROP TABLE assets');
        $this->addSql('DROP TABLE scopes');
        $this->addSql('DROP TABLE threats');
        $this->addSql('DROP TABLE vulnerabilities');
        $this->addSql('DROP TABLE vulnerability_assets');
    }
}
