<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719090902 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create security controls, risk scenarios, configurable thresholds and risk evaluations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE risk_scenarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, likelihood INT NOT NULL, impact INT NOT NULL, gross_risk_score INT NOT NULL, current_likelihood INT NOT NULL, current_impact INT NOT NULL, current_risk_score INT NOT NULL, residual_likelihood INT NOT NULL, residual_impact INT NOT NULL, residual_risk_score INT NOT NULL, treatment_decision VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, review_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, scope_id INT NOT NULL, asset_id INT NOT NULL, threat_id INT NOT NULL, risk_owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4ED385AF32C8A3DE ON risk_scenarios (organization_id)');
        $this->addSql('CREATE INDEX IDX_4ED385AF682B5931 ON risk_scenarios (scope_id)');
        $this->addSql('CREATE INDEX IDX_4ED385AF5DA1941 ON risk_scenarios (asset_id)');
        $this->addSql('CREATE INDEX IDX_4ED385AFB2891786 ON risk_scenarios (threat_id)');
        $this->addSql('CREATE INDEX IDX_4ED385AF98152296 ON risk_scenarios (risk_owner_id)');
        $this->addSql('CREATE TABLE risk_vulnerabilities (risk_scenario_id INT NOT NULL, vulnerability_id INT NOT NULL, PRIMARY KEY (risk_scenario_id, vulnerability_id))');
        $this->addSql('CREATE INDEX IDX_8E6AEDA83A23418E ON risk_vulnerabilities (risk_scenario_id)');
        $this->addSql('CREATE INDEX IDX_8E6AEDA872897D8B ON risk_vulnerabilities (vulnerability_id)');
        $this->addSql('CREATE TABLE risk_security_controls (risk_scenario_id INT NOT NULL, security_control_id INT NOT NULL, PRIMARY KEY (risk_scenario_id, security_control_id))');
        $this->addSql('CREATE INDEX IDX_277604463A23418E ON risk_security_controls (risk_scenario_id)');
        $this->addSql('CREATE INDEX IDX_27760446F26C157B ON risk_security_controls (security_control_id)');
        $this->addSql('CREATE TABLE security_controls (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) NOT NULL, effectiveness INT NOT NULL, implementation_status VARCHAR(30) NOT NULL, owner_id INT DEFAULT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99860BED7E3C61F9 ON security_controls (owner_id)');
        $this->addSql('CREATE INDEX IDX_99860BED32C8A3DE ON security_controls (organization_id)');
        $this->addSql('ALTER TABLE risk_scenarios ADD CONSTRAINT FK_4ED385AF32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE risk_scenarios ADD CONSTRAINT FK_4ED385AF682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE risk_scenarios ADD CONSTRAINT FK_4ED385AF5DA1941 FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE risk_scenarios ADD CONSTRAINT FK_4ED385AFB2891786 FOREIGN KEY (threat_id) REFERENCES threats (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE risk_scenarios ADD CONSTRAINT FK_4ED385AF98152296 FOREIGN KEY (risk_owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE risk_vulnerabilities ADD CONSTRAINT FK_8E6AEDA83A23418E FOREIGN KEY (risk_scenario_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_vulnerabilities ADD CONSTRAINT FK_8E6AEDA872897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_security_controls ADD CONSTRAINT FK_277604463A23418E FOREIGN KEY (risk_scenario_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_security_controls ADD CONSTRAINT FK_27760446F26C157B FOREIGN KEY (security_control_id) REFERENCES security_controls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE security_controls ADD CONSTRAINT FK_99860BED7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_controls ADD CONSTRAINT FK_99860BED32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organizations ADD risk_thresholds JSON DEFAULT \'{"lowMax":4,"moderateMax":9,"highMax":16,"criticalMax":25}\' NOT NULL');
        $this->addSql('ALTER TABLE organizations ALTER risk_thresholds DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE risk_scenarios DROP CONSTRAINT FK_4ED385AF32C8A3DE');
        $this->addSql('ALTER TABLE risk_scenarios DROP CONSTRAINT FK_4ED385AF682B5931');
        $this->addSql('ALTER TABLE risk_scenarios DROP CONSTRAINT FK_4ED385AF5DA1941');
        $this->addSql('ALTER TABLE risk_scenarios DROP CONSTRAINT FK_4ED385AFB2891786');
        $this->addSql('ALTER TABLE risk_scenarios DROP CONSTRAINT FK_4ED385AF98152296');
        $this->addSql('ALTER TABLE risk_vulnerabilities DROP CONSTRAINT FK_8E6AEDA83A23418E');
        $this->addSql('ALTER TABLE risk_vulnerabilities DROP CONSTRAINT FK_8E6AEDA872897D8B');
        $this->addSql('ALTER TABLE risk_security_controls DROP CONSTRAINT FK_277604463A23418E');
        $this->addSql('ALTER TABLE risk_security_controls DROP CONSTRAINT FK_27760446F26C157B');
        $this->addSql('ALTER TABLE security_controls DROP CONSTRAINT FK_99860BED7E3C61F9');
        $this->addSql('ALTER TABLE security_controls DROP CONSTRAINT FK_99860BED32C8A3DE');
        $this->addSql('DROP TABLE risk_scenarios');
        $this->addSql('DROP TABLE risk_vulnerabilities');
        $this->addSql('DROP TABLE risk_security_controls');
        $this->addSql('DROP TABLE security_controls');
        $this->addSql('ALTER TABLE organizations DROP risk_thresholds');
    }
}
