<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260809110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tenant-scoped encrypted AI copilot settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ai_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, provider VARCHAR(20) NOT NULL, base_url VARCHAR(255) NOT NULL, model VARCHAR(120) NOT NULL, encrypted_api_key TEXT DEFAULT NULL, data_policy VARCHAR(20) NOT NULL, system_prompt TEXT NOT NULL, enabled BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FAA326A532C8A3DE ON ai_settings (organization_id)');
        $this->addSql('ALTER TABLE ai_settings ADD CONSTRAINT FK_AI_SETTINGS_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ai_settings');
    }
}
