<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719160755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE continuity_processes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(220) NOT NULL, criticality VARCHAR(20) NOT NULL, mtpd_hours INT NOT NULL, rto_hours INT NOT NULL, rpo_hours INT NOT NULL, dependencies JSON NOT NULL, business_impact TEXT NOT NULL, bcp_procedure TEXT DEFAULT NULL, drp_procedure TEXT DEFAULT NULL, exercises JSON NOT NULL, next_exercise_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, scope_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4AF14B4632C8A3DE ON continuity_processes (organization_id)');
        $this->addSql('CREATE INDEX IDX_4AF14B46682B5931 ON continuity_processes (scope_id)');
        $this->addSql('CREATE INDEX IDX_4AF14B467E3C61F9 ON continuity_processes (owner_id)');
        $this->addSql('CREATE TABLE security_incidents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(220) NOT NULL, description TEXT NOT NULL, severity VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, impacts JSON NOT NULL, timeline JSON NOT NULL, evidence JSON NOT NULL, regulatory_notification_required BOOLEAN NOT NULL, notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lessons_learned TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8EEFEDAF32C8A3DE ON security_incidents (organization_id)');
        $this->addSql('CREATE INDEX IDX_8EEFEDAF7E3C61F9 ON security_incidents (owner_id)');
        $this->addSql('CREATE TABLE incident_assets (security_incident_id INT NOT NULL, asset_id INT NOT NULL, PRIMARY KEY (security_incident_id, asset_id))');
        $this->addSql('CREATE INDEX IDX_D4EDC16A794A68D8 ON incident_assets (security_incident_id)');
        $this->addSql('CREATE INDEX IDX_D4EDC16A5DA1941 ON incident_assets (asset_id)');
        $this->addSql('CREATE TABLE incident_third_parties (security_incident_id INT NOT NULL, third_party_id INT NOT NULL, PRIMARY KEY (security_incident_id, third_party_id))');
        $this->addSql('CREATE INDEX IDX_90F38492794A68D8 ON incident_third_parties (security_incident_id)');
        $this->addSql('CREATE INDEX IDX_90F3849254C4149C ON incident_third_parties (third_party_id)');
        $this->addSql('CREATE TABLE incident_risks (security_incident_id INT NOT NULL, risk_scenario_id INT NOT NULL, PRIMARY KEY (security_incident_id, risk_scenario_id))');
        $this->addSql('CREATE INDEX IDX_41981AB2794A68D8 ON incident_risks (security_incident_id)');
        $this->addSql('CREATE INDEX IDX_41981AB23A23418E ON incident_risks (risk_scenario_id)');
        $this->addSql('CREATE TABLE incident_actions (security_incident_id INT NOT NULL, action_plan_id INT NOT NULL, PRIMARY KEY (security_incident_id, action_plan_id))');
        $this->addSql('CREATE INDEX IDX_A282EB32794A68D8 ON incident_actions (security_incident_id)');
        $this->addSql('CREATE INDEX IDX_A282EB32323B8A7A ON incident_actions (action_plan_id)');
        $this->addSql('ALTER TABLE continuity_processes ADD CONSTRAINT FK_4AF14B4632C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE continuity_processes ADD CONSTRAINT FK_4AF14B46682B5931 FOREIGN KEY (scope_id) REFERENCES scopes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE continuity_processes ADD CONSTRAINT FK_4AF14B467E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_incidents ADD CONSTRAINT FK_8EEFEDAF32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_incidents ADD CONSTRAINT FK_8EEFEDAF7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_assets ADD CONSTRAINT FK_D4EDC16A794A68D8 FOREIGN KEY (security_incident_id) REFERENCES security_incidents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_assets ADD CONSTRAINT FK_D4EDC16A5DA1941 FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_third_parties ADD CONSTRAINT FK_90F38492794A68D8 FOREIGN KEY (security_incident_id) REFERENCES security_incidents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_third_parties ADD CONSTRAINT FK_90F3849254C4149C FOREIGN KEY (third_party_id) REFERENCES third_parties (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_risks ADD CONSTRAINT FK_41981AB2794A68D8 FOREIGN KEY (security_incident_id) REFERENCES security_incidents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_risks ADD CONSTRAINT FK_41981AB23A23418E FOREIGN KEY (risk_scenario_id) REFERENCES risk_scenarios (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_actions ADD CONSTRAINT FK_A282EB32794A68D8 FOREIGN KEY (security_incident_id) REFERENCES security_incidents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE incident_actions ADD CONSTRAINT FK_A282EB32323B8A7A FOREIGN KEY (action_plan_id) REFERENCES action_plans (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE continuity_processes DROP CONSTRAINT FK_4AF14B4632C8A3DE');
        $this->addSql('ALTER TABLE continuity_processes DROP CONSTRAINT FK_4AF14B46682B5931');
        $this->addSql('ALTER TABLE continuity_processes DROP CONSTRAINT FK_4AF14B467E3C61F9');
        $this->addSql('ALTER TABLE security_incidents DROP CONSTRAINT FK_8EEFEDAF32C8A3DE');
        $this->addSql('ALTER TABLE security_incidents DROP CONSTRAINT FK_8EEFEDAF7E3C61F9');
        $this->addSql('ALTER TABLE incident_assets DROP CONSTRAINT FK_D4EDC16A794A68D8');
        $this->addSql('ALTER TABLE incident_assets DROP CONSTRAINT FK_D4EDC16A5DA1941');
        $this->addSql('ALTER TABLE incident_third_parties DROP CONSTRAINT FK_90F38492794A68D8');
        $this->addSql('ALTER TABLE incident_third_parties DROP CONSTRAINT FK_90F3849254C4149C');
        $this->addSql('ALTER TABLE incident_risks DROP CONSTRAINT FK_41981AB2794A68D8');
        $this->addSql('ALTER TABLE incident_risks DROP CONSTRAINT FK_41981AB23A23418E');
        $this->addSql('ALTER TABLE incident_actions DROP CONSTRAINT FK_A282EB32794A68D8');
        $this->addSql('ALTER TABLE incident_actions DROP CONSTRAINT FK_A282EB32323B8A7A');
        $this->addSql('DROP TABLE continuity_processes');
        $this->addSql('DROP TABLE security_incidents');
        $this->addSql('DROP TABLE incident_assets');
        $this->addSql('DROP TABLE incident_third_parties');
        $this->addSql('DROP TABLE incident_risks');
        $this->addSql('DROP TABLE incident_actions');
    }
}
